spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 112167ltd
    url: jdbc:mysql://localhost:3306/sell?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#修改Ribbon的负载均衡策略，改为Random方式
#PRODUCT:
#  ribbon:c
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
server:
  port: 8090